version: '3.7'
services:
  no-cron:
    container_name: no-cron
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /root/no-cron
    environment:
      TZ: Asia/Tokyo
      TEST_CRON_ENV: no-cron
    # Only active system cron
    # command: /bin/sh -c "crond -b && tail -f /logs/cron.log"
    # Only active no-cron
    # command: /bin/sh -c "pm2 start cron.js && tail -f /logs/cron.log"
    # Both active system cron and no-cron
    command: /bin/sh -c "pm2 start cron.js && crond -b && tail -f /logs/cron.log"
